services:
  mongodb:
    image: 'mongo:latest'
    container_name: gastromind-mongo-${ENV_NAME}
    environment:
      - 'MONGO_INITDB_DATABASE=${DB_NAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}'
    ports:
      - '${MONGO_PORT}:27017'
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: 'postgres:latest'
    container_name: gastromind-postgres-${ENV_NAME}
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASS}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pgdata-${ENV_NAME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:alpine'
    container_name: gastromind-redis-${ENV_NAME}
    ports:
      - '${REDIS_PORT}:6379'

  pgadmin:
    image: dpage/pgadmin4
    container_name: gastromind-pgadmin-${ENV_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - postgres
      - redis

volumes:
  pgdata-dev:
  pgdata-prod: